# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import json

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
city_df = pd.read_csv("city_data.csv")
city_df

,City,Latitude,Longitude,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,Port Alfred,-33.59,26.89,53.13,50,7,13.47,ZA,1597900628
1,Altamira,-3.20,-52.21,74.79,60,23,2.39,BR,1597900629
2,Havre-St-Pierre,50.23,-63.60,59.00,82,90,6.93,CA,1597900629
3,Bluff,-46.60,168.33,48.99,93,100,7.00,NZ,1597900629
4,Barrow,71.29,-156.79,39.20,93,90,9.17,US,1597900629
...,...,...,...,...,...,...,...,...,...
582,Chui,-33.70,-53.46,40.66,75,31,9.82,UY,1597900815
583,Pangody,65.85,74.49,64.90,66,29,9.06,RU,1597900816
584,Terrace,54.52,-128.60,55.40,93,90,18.34,CA,1597900816
585,Tual,-5.67,132.75,79.00,82,3,14.50,ID,1597900816
586,Eyl,7.98,49.82,82.96,62,60,22.08,SO,1597900816

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
# Configure gmaps
gmaps.configure(api_key=g_key)

# Use the Lat and Lng as locations and Humidity as the weight
locations = city_df[["Latitude", "Longitude"]]
weight = city_df["Humidity"]

In [8]:
# Plot Heatmap
fig = gmaps.figure(center=(20.0, 5.0), zoom_level=2)

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=weight, 
                                 dissipating=False, max_intensity=np.max(weight),
                                 point_radius=1)


# Add layer
fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [9]:
# Narrow down the cities to fit weather conditions
narrow = city_df.loc[(city_df["Max Temp"] < 80) & (city_df["Max Temp"] > 70) & (city_df["Wind Speed"] < 10) &
                     (city_df["Cloudiness"] == 0)]
narrow

,City,Latitude,Longitude,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
17,Zliten,32.47,14.57,77.13,78,0,2.06,LY,1597900527
65,Sakakah,29.97,40.21,77.00,20,0,4.70,SA,1597900647
79,Kiryat Gat,31.61,34.76,75.99,11,0,3.85,IL,1597900590
107,Kropotkin,45.44,40.58,78.73,34,0,6.24,RU,1597900662
144,Borba,-4.39,-59.59,78.06,56,0,2.42,BR,1597900673
155,Jacareacanga,-6.22,-57.75,74.82,54,0,0.98,BR,1597900522
169,Bouloupari,-21.87,166.05,78.80,61,0,8.05,NC,1597900680
171,Syracuse,37.09,15.28,71.60,88,0,6.93,IT,1597900680
216,Ben Gardane,33.14,11.22,76.44,77,0,4.97,TN,1597900692
233,Harsīn,34.27,47.59,73.40,13,0,4.70,IR,1597900697
259,Mahon,39.89,4.27,73.40,94,0,5.82,ES,1597900709
274,Chihuahua,28.50,-106.00,77.00,33,0,1.99,MX,1597900626
304,Jūybār,36.64,52.91,75.20,83,0,6.93,IR,1597900726
305,Sitges,41.24,1.81,75.00,85,0,2.51,ES,1597900727
328,Litovko,49.24,135.17,72.45,57,0,9.22,RU,1597900734
386,Rosetta,31.40,30.42,78.80,69,0,6.93,EG,1597900754
391,Airai,-8.93,125.41,78.96,32,0,3.85,TL,1597900755
403,San Quintín,30.48,-115.95,74.84,76,0,8.93,MX,1597900759
446,Romitan,39.93,64.38,78.80,29,0,6.93,UZ,1597900773
458,Samarai,-10.62,150.67,77.54,72,0,8.12,PG,1597900778
462,São João da Barra,-21.64,-41.05,70.70,89,0,3.87,BR,1597900779
515,Poum,-20.23,164.02,73.60,71,0,8.08,NC,1597900796
529,Santa Helena de Goiás,-17.81,-50.60,70.43,60,0,9.08,BR,1597900799
549,Châteauneuf-les-Martigues,43.38,5.17,73.99,68,0,5.82,FR,1597900806
553,Oruzgan,32.83,66.00,79.48,16,0,3.87,AF,1597900807
567,Alta Floresta,-9.88,-56.09,73.81,34,0,1.66,BR,1597900811

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [10]:
# Store into variable named hotel_df
hotel_df = narrow[["City", "Country", "Latitude", "Longitude"]]

# Add a "Hotel Name" column to the DataFrame
hotel_df["Hotel Name"] = ""
hotel_df

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

                          City Country  Latitude  Longitude Hotel Name
17                      Zliten      LY     32.47      14.57
65                     Sakakah      SA     29.97      40.21
79                  Kiryat Gat      IL     31.61      34.76
107                  Kropotkin      RU     45.44      40.58
144                      Borba      BR     -4.39     -59.59
155               Jacareacanga      BR     -6.22     -57.75
169                 Bouloupari      NC    -21.87     166.05
171                   Syracuse      IT     37.09      15.28
216                Ben Gardane      TN     33.14      11.22
233                     Harsīn      IR     34.27      47.59
259                      Mahon      ES     39.89       4.27
274                  Chihuahua      MX     28.50    -106.00
304                     Jūybār      IR     36.64      52.91
305                     Sitges      ES     41.24       1.81
328                    Litovko      RU     49.24     135.17
386                    Rosetta      EG     31.40      30.42
391                      Airai      TL     -8.93     125.41
403                San Quintín      MX     30.48    -115.95
446                    Romitan      UZ     39.93      64.38
458                    Samarai      PG    -10.62     150.67
462          São João da Barra      BR    -21.64     -41.05
515                       Poum      NC    -20.23     164.02
529      Santa Helena de Goiás      BR    -17.81     -50.60
549  Châteauneuf-les-Martigues      FR     43.38       5.17
553                    Oruzgan      AF     32.83      66.00
567              Alta Floresta      BR     -9.88     -56.09

In [11]:
# Set parameters to search for hotels with 5000 meters
params = {
    "radius" : 5000,
    "keyword" : "hotel",
    "types": "hotel",
    "key": g_key
}

# Hit the Google Places API for each city's coordinates.
for index, row in hotel_df.iterrows():
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # get cities, etc. from hotel_df
    city = row['City']
    lat = row['Latitude']
    lng = row['Longitude']

    # add keyword to params dict
    params["location"] = f"{lat},{lng}"

    # assemble url and make API request
    print(f"Retrieving Results for Index {index}: {city}.")
    response = requests.get(base_url, params=params).json()
#     print(json.dumps(response, indent= 4, sort_keys= True))
    
    # print the response url, avoid doing for public github repos in order to avoid exposing key
#     print(response)
    
    # extract results 
    results = response['results']
  
    try:
        print(f"Closest hotel in {city} is {results[0]['name']}.")
        
        hotel_df.loc[index, 'Hotel Name'] = results[0]['name']
        
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")
        
    print("------------")

Retrieving Results for Index 17: Zliten.
Closest hotel in Zliten is فندق الهادي العاتي.
------------
Retrieving Results for Index 65: Sakakah.

/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:965: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

Closest hotel in Sakakah is Raoum Inn Hotel.
------------
Retrieving Results for Index 79: Kiryat Gat.
Closest hotel in Kiryat Gat is Desert Gat.
------------
Retrieving Results for Index 107: Kropotkin.
Closest hotel in Kropotkin is Luxury House ECO-hotel & Spa.
------------
Retrieving Results for Index 144: Borba.
Closest hotel in Borba is Hotel Borbo Palace.
------------
Retrieving Results for Index 155: Jacareacanga.
Closest hotel in Jacareacanga is HOTEL VIANA.
------------
Retrieving Results for Index 169: Bouloupari.
Closest hotel in Bouloupari is Oua-Ya Lodge.
------------
Retrieving Results for Index 171: Syracuse.
Closest hotel in Syracuse is Charme Hotel Henry's House / Hotel Ortigia.
------------
Retrieving Results for Index 216: Ben Gardane.
Closest hotel in Ben Gardane is Hôtel Palace.
------------
Retrieving Results for Index 233: Harsīn.
Missing field/result... skipping.
------------
Retrieving Results for Index 259: Mahon.
Closest hotel in Mahon is Casa Ládico Boutique Hotel.
------------
Retrieving Results for Index 274: Chihuahua.
Missing field/result... skipping.
------------
Retrieving Results for Index 304: Jūybār.
Closest hotel in Jūybār is هتل و تالار سامان.
------------
Retrieving Results for Index 305: Sitges.
Closest hotel in Sitges is Hotel Calipolis.
------------
Retrieving Results for Index 328: Litovko.
Missing field/result... skipping.
------------
Retrieving Results for Index 386: Rosetta.
Closest hotel in Rosetta is Mecca Hotel.
------------
Retrieving Results for Index 391: Airai.
Missing field/result... skipping.
------------
Retrieving Results for Index 403: San Quintín.
Closest hotel in San Quintín is Old Mill Hotel.
------------
Retrieving Results for Index 446: Romitan.
Missing field/result... skipping.
------------
Retrieving Results for Index 458: Samarai.
Closest hotel in Samarai is Nuli Sapi.
------------
Retrieving Results for Index 462: São João da Barra.
Closest hotel in São João da Barra is OYO Pousada Mediterrâneo.
------------
Retrieving Results for Index 515: Poum.
Missing field/result... skipping.
------------
Retrieving Results for Index 529: Santa Helena de Goiás.
Closest hotel in Santa Helena de Goiás is Castro Castle Hotel.
------------
Retrieving Results for Index 549: Châteauneuf-les-Martigues.
Closest hotel in Châteauneuf-les-Martigues is Hotel Restaurant L'Hacienda.
------------
Retrieving Results for Index 553: Oruzgan.
Missing field/result... skipping.
------------
Retrieving Results for Index 567: Alta Floresta.
Closest hotel in Alta Floresta is Lisboa Palace Hotel.
------------

In [12]:
hotel_df

,City,Country,Latitude,Longitude,Hotel Name
17,Zliten,LY,32.47,14.57,فندق الهادي العاتي
65,Sakakah,SA,29.97,40.21,Raoum Inn Hotel
79,Kiryat Gat,IL,31.61,34.76,Desert Gat
107,Kropotkin,RU,45.44,40.58,Luxury House ECO-hotel & Spa
144,Borba,BR,-4.39,-59.59,Hotel Borbo Palace
155,Jacareacanga,BR,-6.22,-57.75,HOTEL VIANA
169,Bouloupari,NC,-21.87,166.05,Oua-Ya Lodge
171,Syracuse,IT,37.09,15.28,Charme Hotel Henry's House / Hotel Ortigia
216,Ben Gardane,TN,33.14,11.22,Hôtel Palace
233,Harsīn,IR,34.27,47.59,
259,Mahon,ES,39.89,4.27,Casa Ládico Boutique Hotel
274,Chihuahua,MX,28.50,-106.00,
304,Jūybār,IR,36.64,52.91,هتل و تالار سامان
305,Sitges,ES,41.24,1.81,Hotel Calipolis
328,Litovko,RU,49.24,135.17,
386,Rosetta,EG,31.40,30.42,Mecca Hotel
391,Airai,TL,-8.93,125.41,
403,San Quintín,MX,30.48,-115.95,Old Mill Hotel
446,Romitan,UZ,39.93,64.38,
458,Samarai,PG,-10.62,150.67,Nuli Sapi
462,São João da Barra,BR,-21.64,-41.05,OYO Pousada Mediterrâneo
515,Poum,NC,-20.23,164.02,
529,Santa Helena de Goiás,BR,-17.81,-50.60,Castro Castle Hotel
549,Châteauneuf-les-Martigues,FR,43.38,5.17,Hotel Restaurant L'Hacienda
553,Oruzgan,AF,32.83,66.00,
567,Alta Floresta,BR,-9.88,-56.09,Lisboa Palace Hotel

In [13]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
hotel_locations = hotel_df[["Latitude", "Longitude"]]

In [14]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(hotel_locations)

hotel_layer = gmaps.symbol_layer(
    hotel_locations, fill_color='rgba(0, 150, 0, 0.4)',
    stroke_color='rgba(0, 0, 150, 0.4)', scale=2,
    info_box_content=hotel_info)

# Display figure
fig.add_layer(markers)
fig.add_layer(hotel_layer)
fig

Figure(layout=FigureLayout(height='420px'))